apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- monitoring.yaml
- persistent-volume.yaml
- cluster-role.yaml
- service-account.yaml
- cluster-role-binding.yaml
- prometheus-config-map.yaml
- prometheus-deployment.yaml
- prometheus-service.yaml
- alertmanager-config-map.yaml
- alertmanager-deployment.yaml
- alertmanager-service.yaml
