apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prometheus-data
  namespace: monitoring
  labels:
    type: nfs
    app: prometheus-deployment
spec:
  storageClassName: managed-nfs
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.56.20
    path: "/mnt/nfs/prometheus-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-prometheus-data
  namespace: monitoring
  labels:
    app: prometheus-deployment
spec:
  storageClassName: managed-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi